### ISSUE TITLE
More a question than an issue

### ISSUE THREAD

**Issue by franckflo** [am-a/journal-search#1]
Hi, I've been looking for this functionality for a while, so thanks for creating a module about it!

I'm not sure how that works. I use Foundry v10 and no module changing the Journal function. When I type a keyword in the journal search (top of the tab), the only returned items are those with the searched term in their title. Am I using this incorrectly ?

**Comment by am-a** [comment]
Hi @franckflo - This may have been a bug. Try updating to the latest (v0.0.6) version!

I think was was happening before is that the results are being hidden

**Comment by am-a** [comment]
@franckflo it should look like this: 
![image](https://user-images.githubusercontent.com/627367/218495099-8837badb-6cd2-4381-be53-6e06692e3279.png)

**Comment by franckflo** [comment]
Got it. That works, I actually was hoping the module was allowing to search within Journals at the tab level. Right now it only looks for terms that are in the subject line.

**Comment by am-a** [comment]
Hi @franckflo - The way it works is that extends the default search of Foundry by checking the contents of the page (vs Foundry only using the page titles).

So if a match within the page is found, a preview will be generated and appear under the heading of the relevant page.

If the match is only within the header of the page, there will be no preview but the page will be still be in the list (this is the default Foundry behaviour).

Can you explain what you mean by searching within journals at tab level? Do you mean all the journals available?

**Comment by franckflo** [comment]
What I meant is that I was looking for a module where I can perform a search on the Journal Tab on the top right of the FVTT interface. It would look for the searched term inside all the journals (not just their title).

**Comment by am-a** [comment]
Ah I see @franckflo - I'll add it as an enhancement. Thanks for the feedback!

**Comment by franckflo** [comment]
That's wonderful, thanks!

**Comment by am-a** [comment]
@franckflo - 0.0.7 should now include that functionality
