### ISSUE TITLE
Search only pages the user has access to

### ISSUE THREAD

**Issue by arirawr** [am-a/journal-search#3]
I have a document with multiple pages (in this case, a quest log), where players do not have access to all pages.
When using search from the sidebar, players can see the titles and snippets of pages to which they don't have access.

Potential solutions:
- GM toggle to disable players from using search altogether
- Only searching pages with appropriate visibility (observer and owner, probably)

My current workaround is to disable sidebar search, but I would really like to have this feature.

**Comment by am-a** [comment]
@arirawr - that was an oversight on my part! Will have a fix out in the next version and tag when released

**Comment by am-a** [comment]
@arirawr - fixed in v0.0.8
