### ISSUE TITLE
Firefox does not support `:has` CSS selector

### ISSUE THREAD

**Issue by TheGiddyLimit** [am-a/journal-search#4]
As per title, latest Firefox gates this feature behind a disabled-by-default flag; [see MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/:has#browser_compatibility).

This causes crashes when e.g. [this line is triggered](https://github.com/am-a/journal-search/blob/7feb1a2b04587c77548084fd92f10eb7131031ce/src/wrappers/journal-sheet/_on-search-filter.ts#L12).

**Comment by am-a** [comment]
@TheGiddyLimit - Good catch. Will amend and make sure to test in Firefox in future!

**Comment by am-a** [comment]
@TheGiddyLimit - Should be fixed in v.0.0.9
